// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTdz_K00g5MrXJ21FgOvZ11cK0HTLZpVQ',
    appId: '1:629540273768:web:1e358803a0249d9361c5dd',
    messagingSenderId: '629540273768',
    projectId: 'cloudnote-837d8',
    authDomain: 'cloudnote-837d8.firebaseapp.com',
    storageBucket: 'cloudnote-837d8.appspot.com',
    measurementId: 'G-2VMG92RJ1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAr5IzbMHPuWBZu-E9iGiWq4cmtH8BThg',
    appId: '1:629540273768:android:19b0771f2d93c7ec61c5dd',
    messagingSenderId: '629540273768',
    projectId: 'cloudnote-837d8',
    storageBucket: 'cloudnote-837d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD1sjAA1vrzJwX_r9juq-AAY6eiM8O8vo',
    appId: '1:629540273768:ios:a0e50313c56ae13761c5dd',
    messagingSenderId: '629540273768',
    projectId: 'cloudnote-837d8',
    storageBucket: 'cloudnote-837d8.appspot.com',
    iosClientId: '629540273768-g978sa3pa55pfs2lg1ubml2tqqs44g2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudnote',
  );
}
